#Server port configurations
server:
  port: 6060
  
#Database Configurations
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: boot_dev
    password: boot_dev
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
#logging configuration
logging:  file:    name: D:\\Ashok IT School\\SpringBoot-Cloud-MicroServices\\Work-Space\\logs\\CustomerRest.log