#Server port configurations
server:
  port: 6161
  
#Database Configurations
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: boot_qa
    password: boot_qa
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
      
      
      
      
  